### ISSUE TITLE
0.8.1 install error: Could not resolve dependency @nomiclabs/hardhat-ethers@"npm:hardhat-deploy-ethers@^0.3.0-beta.10"

### ISSUE THREAD

**Issue by deanpress** [antoinedc/hardhat-ethernal#22] opened 2022-05-07 15:01 UTC
Console log:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: hardhat-project@undefined
npm ERR! Found: @nomiclabs/hardhat-ethers@2.0.5
npm ERR! node_modules/@nomiclabs/hardhat-ethers
npm ERR!   dev @nomiclabs/hardhat-ethers@"^2.0.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nomiclabs/hardhat-ethers@"npm:hardhat-deploy-ethers@^0.3.0-beta.10" from hardhat-ethernal@0.8.1
npm ERR! node_modules/hardhat-ethernal
npm ERR!   dev hardhat-ethernal@"^0.8.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

package.json:
```
{
  "name": "hardhat-project",
  "devDependencies": {
    "@nomiclabs/hardhat-ethers": "^2.0.5",
    "@nomiclabs/hardhat-waffle": "^2.0.3",
    "chai": "^4.3.6",
    "dotenv": "^16.0.0",
    "ethereum-waffle": "^3.4.0",
    "ethers": "^5.5.4",
    "hardhat": "^2.9.0",
    "hardhat-contract-sizer": "^2.5.0",
    "hardhat-gas-reporter": "^1.0.8",
    "hardhat-ethernal": "^0.8.1"
  },
  "dependencies": {
    "@openzeppelin/contracts": "^4.5.0"
  }
}
```

**Comment by antoinedc** [comment] 2022-05-07 15:18
Are you using npm or yarn?

If npm, can you run `npm install --force`?

**Comment by Jhoscy** [comment] 2022-05-07 15:21
We have the same problem and I wanted to ask you why are using a "beta" as dependecy for Ethernal instead of the stable 2.0.5

**Comment by antoinedc** [comment] 2022-05-07 15:24
Because of how Hardhat plugins work, Ethernal has to use the ethers version that is included in hardhat-deploy-ethers.
The "beta" version is the version of hardhat-deploy-ethers, which uses and exports ethers v2.0.5.

**Comment by Jhoscy** [comment] 2022-05-07 16:26
> Console log:
> 
> ```
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: hardhat-project@undefined
> npm ERR! Found: @nomiclabs/hardhat-ethers@2.0.5
> npm ERR! node_modules/@nomiclabs/hardhat-ethers
> npm ERR!   dev @nomiclabs/hardhat-ethers@"^2.0.5" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer @nomiclabs/hardhat-ethers@"npm:hardhat-deploy-ethers@^0.3.0-beta.10" from hardhat-ethernal@0.8.1
> npm ERR! node_modules/hardhat-ethernal
> npm ERR!   dev hardhat-ethernal@"^0.8.1" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> ```
> 
> package.json:
> 
> ```
> {
>   "name": "hardhat-project",
>   "devDependencies": {
>     "@nomiclabs/hardhat-ethers": "^2.0.5",
>     "@nomiclabs/hardhat-waffle": "^2.0.3",
>     "chai": "^4.3.6",
>     "dotenv": "^16.0.0",
>     "ethereum-waffle": "^3.4.0",
>     "ethers": "^5.5.4",
>     "hardhat": "^2.9.0",
>     "hardhat-contract-sizer": "^2.5.0",
>     "hardhat-gas-reporter": "^1.0.8",
>     "hardhat-ethernal": "^0.8.1"
>   },
>   "dependencies": {
>     "@openzeppelin/contracts": "^4.5.0"
>   }
> }
> ```

I faced the same error and I fixed installing:   "@nomiclabs/hardhat-ethers": "npm:hardhat-deploy-ethers@^0.3.0-beta.13".
If you are working using Linux (like me), you can get another error (not on MacOS) about keytar.
In that case you need to run: sudo apt-get install libsecret-1-dev.
Then, if you run npm i (with hardhat-ethernal 0.8.1), it works.

**Comment by Jhoscy** [comment] 2022-05-07 16:29
On hardhat-ethernal 0.8.1 we are speaking with Antoine about changing in:
hardhat-ethernal/dist/type-extensions.d.ts from 
```
declare module "hardhat/types/config" {
    interface HardhatConfig {
        disableEthernal?: boolean;
    }
}
```

to

```
declare module "hardhat/types/config" {
    interface HardhatUserConfig {
        disableEthernal?: boolean;
    }
}
```

in order to not get static error in hardhat.config.js about disableEthernal

**Comment by antoinedc** [comment] 2022-05-09 16:20
> > Console log:
> > ```
> > npm ERR! code ERESOLVE
> > npm ERR! ERESOLVE unable to resolve dependency tree
> > npm ERR!
> > npm ERR! While resolving: hardhat-project@undefined
> > npm ERR! Found: @nomiclabs/hardhat-ethers@2.0.5
> > npm ERR! node_modules/@nomiclabs/hardhat-ethers
> > npm ERR!   dev @nomiclabs/hardhat-ethers@"^2.0.5" from the root project
> > npm ERR! 
> > npm ERR! Could not resolve dependency:
> > npm ERR! peer @nomiclabs/hardhat-ethers@"npm:hardhat-deploy-ethers@^0.3.0-beta.10" from hardhat-ethernal@0.8.1
> > npm ERR! node_modules/hardhat-ethernal
> > npm ERR!   dev hardhat-ethernal@"^0.8.1" from the root project
> > npm ERR!
> > npm ERR! Fix the upstream dependency conflict, or retry
> > npm ERR! this command with --force, or --legacy-peer-deps
> > npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > package.json:
> > ```
> > {
> >   "name": "hardhat-project",
> >   "devDependencies": {
> >     "@nomiclabs/hardhat-ethers": "^2.0.5",
> >     "@nomiclabs/hardhat-waffle": "^2.0.3",
> >     "chai": "^4.3.6",
> >     "dotenv": "^16.0.0",
> >     "ethereum-waffle": "^3.4.0",
> >     "ethers": "^5.5.4",
> >     "hardhat": "^2.9.0",
> >     "hardhat-contract-sizer": "^2.5.0",
> >     "hardhat-gas-reporter": "^1.0.8",
> >     "hardhat-ethernal": "^0.8.1"
> >   },
> >   "dependencies": {
> >     "@openzeppelin/contracts": "^4.5.0"
> >   }
> > }
> > ```
> 
> I faced the same error and I fixed installing: "@nomiclabs/hardhat-ethers": "npm:hardhat-deploy-ethers@^0.3.0-beta.13". If you are working using Linux (like me), you can get another error (not on MacOS) about keytar. In that case you need to run: sudo apt-get install libsecret-1-dev. Then, if you run npm i (with hardhat-ethernal 0.8.1), it works.

Sorry I'm not sure what is the fix you are mentioning here. Do you mind explaining?

At the moment, the only fix I'm aware of for the dependency issue is to either use yarn or the `--force` flag with npm.

**Comment by zeroarst** [comment] 2022-06-28 10:36
I am having the same issue..
and I use --force and --legacy-peer-deps. It works fine. But if I want to install other deps, I got these error:
![image](https://user-images.githubusercontent.com/1834837/176158706-f324244f-21d7-4186-af45-1d7124e6cf05.png)

I need to uninstall hardhat-ethernal, install ohter deps, and try install hardhat-ethernal with --force or --legacy-peer-deps again...

**Comment by ludekvodicka** [comment] 2022-10-19 09:59
Hi,

I have the same issue with 2.2.0 version of hardhat-ethers and 2.1.0 of hardhat-ethernals. Is there any solution for this, or it's necessary to use it together with --force flag only?

```
{
  "dependencies": {
    "@nomicfoundation/hardhat-toolbox": "^2.0.0",
    "@nomiclabs/hardhat-ethers": "^2.2.0",
    "@openzeppelin/contracts": "^4.7.3",
    "hardhat": "^2.12.0",
    "hardhat-ethernal": "^2.1.0"
  },
  "devDependencies": {
    "ts-node": "^10.9.1",
    "typescript": "^4.8.4"
  }
}
```

```

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: hardhat-ethernal@2.1.0
npm ERR! Found: @nomiclabs/hardhat-ethers@2.2.0
npm ERR! node_modules/@nomiclabs/hardhat-ethers
npm ERR!   @nomiclabs/hardhat-ethers@"^2.2.0" from the root project
npm ERR!   peer @nomiclabs/hardhat-ethers@"^2.0.0" from @nomicfoundation/hardhat-chai-matchers@1.0.4
npm ERR!   node_modules/@nomicfoundation/hardhat-chai-matchers
npm ERR!     peer @nomicfoundation/hardhat-chai-matchers@"^1.0.0" from @nomicfoundation/hardhat-toolbox@2.0.0
npm ERR!     node_modules/@nomicfoundation/hardhat-toolbox
npm ERR!       @nomicfoundation/hardhat-toolbox@"^2.0.0" from the root project
npm ERR!   1 more (@nomicfoundation/hardhat-toolbox)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @nomiclabs/hardhat-ethers@"npm:hardhat-deploy-ethers@^0.3.0-beta.10" from hardhat-ethernal@2.1.0
npm ERR! node_modules/hardhat-ethernal
npm ERR!   hardhat-ethernal@"^2.1.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @nomiclabs/hardhat-ethers@0.3.0-beta.13
npm ERR! node_modules/@nomiclabs/hardhat-ethers
npm ERR!   peer @nomiclabs/hardhat-ethers@"npm:hardhat-deploy-ethers@^0.3.0-beta.10" from hardhat-ethernal@2.1.0
npm ERR!   node_modules/hardhat-ethernal
npm ERR!     hardhat-ethernal@"^2.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

```

**Comment by antoinedc** [comment] 2022-10-19 10:01
Hi,

Yes, at the moment, you have to use the --force flag to install it unfortunately.

**Comment by ludekvodicka** [comment] 2022-10-19 10:46
> 

thanks for the quick reply. Is there any eta for fixing this?

**Comment by antoinedc** [comment] 2022-10-19 12:03
Not yet, last time I checked, this issue was still coming from a conflict due to how Hardhat handles plugins.

My assumption was that using the --force flag shouldn't be an issue in general. Is there a reason for you to not use it?

**Comment by ludekvodicka** [comment] 2022-10-19 17:25
I think the issue is that hardhat already using beta.13 and your plugin beta.10. But maybe there is some other issue.

Regarding --force, the issue is that as soon as you use it once, you have to use it always, because it's not possible to call any other next "npm i " command without --force anymore.

**Comment by antoinedc** [comment] 2022-10-21 07:59
I'll take a look at those versions.

I see. And have you tried using yarn instead of npm? I think it works without the force flag

**Comment by Metroxe** [comment] 2022-11-04 21:06
I installed with `npm install --legacy-peer-deps` and got it to work. Probably not ideal, but should work until things are resolved.

**Comment by hgouveia** [comment] 2022-12-05 16:24
Same issue with `hardhat@2.12.1` , i dont want to use force

```shell
$ npm i -D hardhat-ethernal

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: hardhat-project@undefined
npm ERR! Found: @nomiclabs/hardhat-ethers@2.2.1
npm ERR! node_modules/@nomiclabs/hardhat-ethers
npm ERR!   peer @nomiclabs/hardhat-ethers@"^2.0.0" from @nomicfoundation/hardhat-chai-matchers@1.0.4
npm ERR!   node_modules/@nomicfoundation/hardhat-chai-matchers
npm ERR!     peer @nomicfoundation/hardhat-chai-matchers@"^1.0.0" from @nomicfoundation/hardhat-toolbox@2.0.0
npm ERR!     node_modules/@nomicfoundation/hardhat-toolbox
npm ERR!       dev @nomicfoundation/hardhat-toolbox@"^2.0.0" from the root project
npm ERR!   peer @nomiclabs/hardhat-ethers@"^2.0.0" from @nomicfoundation/hardhat-toolbox@2.0.0
npm ERR!   node_modules/@nomicfoundation/hardhat-toolbox
npm ERR!     dev @nomicfoundation/hardhat-toolbox@"^2.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev hardhat-ethernal@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @nomiclabs/hardhat-ethers@0.3.0-beta.13
npm ERR! node_modules/@nomiclabs/hardhat-ethers
npm ERR!   peer @nomiclabs/hardhat-ethers@"npm:hardhat-deploy-ethers@^0.3.0-beta.10" from hardhat-ethernal@3.0.1
npm ERR!   node_modules/hardhat-ethernal
npm ERR!     dev hardhat-ethernal@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\{user}\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\{user}\AppData\Local\npm-cache\_logs\2022-12-05T16_20_25_332Z-debug-0.log
```

**Comment by tansanDOTeth** [comment] 2022-12-13 14:17
Same issue for me

> Same issue with `hardhat@2.12.1` , i dont want to use force
> 
> ```shell
> $ npm i -D hardhat-ethernal
> 
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE could not resolve
> npm ERR!
> npm ERR! While resolving: hardhat-project@undefined
> npm ERR! Found: @nomiclabs/hardhat-ethers@2.2.1
> npm ERR! node_modules/@nomiclabs/hardhat-ethers
> npm ERR!   peer @nomiclabs/hardhat-ethers@"^2.0.0" from @nomicfoundation/hardhat-chai-matchers@1.0.4
> npm ERR!   node_modules/@nomicfoundation/hardhat-chai-matchers
> npm ERR!     peer @nomicfoundation/hardhat-chai-matchers@"^1.0.0" from @nomicfoundation/hardhat-toolbox@2.0.0
> npm ERR!     node_modules/@nomicfoundation/hardhat-toolbox
> npm ERR!       dev @nomicfoundation/hardhat-toolbox@"^2.0.0" from the root project
> npm ERR!   peer @nomiclabs/hardhat-ethers@"^2.0.0" from @nomicfoundation/hardhat-toolbox@2.0.0
> npm ERR!   node_modules/@nomicfoundation/hardhat-toolbox
> npm ERR!     dev @nomicfoundation/hardhat-toolbox@"^2.0.0" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! dev hardhat-ethernal@"*" from the root project
> npm ERR!
> npm ERR! Conflicting peer dependency: @nomiclabs/hardhat-ethers@0.3.0-beta.13
> npm ERR! node_modules/@nomiclabs/hardhat-ethers
> npm ERR!   peer @nomiclabs/hardhat-ethers@"npm:hardhat-deploy-ethers@^0.3.0-beta.10" from hardhat-ethernal@3.0.1
> npm ERR!   node_modules/hardhat-ethernal
> npm ERR!     dev hardhat-ethernal@"*" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR! See C:\Users\{user}\AppData\Local\npm-cache\eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\{user}\AppData\Local\npm-cache\_logs\2022-12-05T16_20_25_332Z-debug-0.log
> ```

**Comment by devrajsinghrawat** [comment] 2023-06-04 18:01
This works for me 

```
npm install --legacy-peer-deps hardhat-ethernal

```

**Comment by johngrimsey** [comment] 2023-08-18 13:02
Hey, it's been a while on this one - possible to fix so `force` or `legacy-peer-deps`  aren't needed? I see the config typings have made their way into Hardhat, perhaps that's relevant, not 100% sure.

**Comment by antoinedc** [comment] 2023-08-18 21:39
> Hey, it's been a while on this one - possible to fix so `force` or `legacy-peer-deps` aren't needed? I see the config typings have made their way into Hardhat, perhaps that's relevant, not 100% sure.

Thanks  for the ping! I started to work on it. Packages upgrade seem to be more complex than what I thought though

**Comment by antoinedc** [comment] 2023-08-19 15:47
I've pushed a new version: 3.2.3 that should fix the issue. Please, let me know if that works

**Comment by johngrimsey** [comment] 2023-08-21 15:28
Thanks @antoinedc will get back to you

**Comment by antoinedc** [comment] 2023-08-25 12:56
Closing this for now, feel free to comment/reopen if the problem is still here.

**Closed as completed by antoinedc** 2023-08-25 12:56 UTC
